// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phhpwlrbsdvwtbevywjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoaHB3bHJic2R2d3RiZXZ5d2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMzUwNTEsImV4cCI6MjA1NjYxMTA1MX0.IgIwLnQfbYivJ2Sg48og_7zP45c0Fmka_KAvX0SStrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);