// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bguhoroceezcneqfrdkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndWhvcm9jZWV6Y25lcWZyZGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMDQyMDgsImV4cCI6MjA1NjY4MDIwOH0.7F0GFeg382m5_n_8mko5W4Tny-hJ150LTilNWgOeGUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);